### ISSUE TITLE
Error while obfucation

### ISSUE THREAD

**Issue by Mrgaton** [AnErrupTion/LoGiC.NET#10]
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Mrgato\Desktop\TokenJuaker_protected.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at LoGiC.NET.Program.Main(String[] args)

i think because the obfucator tryes to make the file in desktop when thath is not my path i realy prefere to save the obfuscated file creating a directory named confused and then saving it inside

**Comment by AnErrupTion** [comment]
I think that happens when trying to inject the Anti-Tamper MD5 into the file. It doesn't actually find the file. The obfuscation most likely failed, but I'm not sure. Do you know it generated an obfuscated file or not? @Mrgaton

**Comment by fgalmeida** [comment]
This is because your windows is in user administrator, create a folder in 'C:\Users\' with the name 'Mrgato' and inside create 'Desktop'

@AnErrupTion change the path where the obfuscated file will be saved!

**Comment by Mrgaton** [comment]
I don't know I just changed already to confuser es it was probably my fault so don't wory
