### ISSUE TITLE
Error & SharpConfigParser missing

### ISSUE THREAD

**Issue by quentinhardy** [AnErrupTion/LoGiC.NET#4]
Hello,

Thank you for this project,

I have the following error with my file:
```
Preparing obfuscation...
Renaming...
  Renamed 1560 methods.
  Renamed 1508 parameters.
  Renamed 883 properties.
  Renamed 580 fields.
  Renamed 0 events.
Adding junk methods...
  Added 3666 junk methods.
Adding proxy calls...
  Added 2059 proxy calls.
Encoding ints...

Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
   at LoGiC.NET.Utils.Randomizer.GenerateRandomString(Int32 size)
   at LoGiC.NET.Protections.IntEncoding.Execute()
   at LoGiC.NET.Program.Main(String[] _)
```
Moreover, it seems _SharpConfigParser_ is missing.

Thank you in advance for your help,

**Comment by AnErrupTion** [comment]
That OverflowException error is because of the integer encoding. Pardon my skills :)

Anyways, for SharpConfigParser, you can get it from the latest release.
